
init_editor = () ->
  console.log 'WOOT'

  $('div#editor').editable
    inlineMode: false
    paragraphy: false
    placeholder: 'Upon inspiration, start typing...'
    colors: [
      '#5BD59B',
      '#428CBD',
      '#945BD5',
      '#f06d6c',
      '#A33A39',
      '#F0723C',
      '#27D085',
      '#2a6b9c',
      '#7b27d0',
      '#f5362e',
      '#802723',
      '#ed5306'
    ]
    colorsStep: 6
    buttons: [
      'bold'
      'italic'
      'underline'
      'strikeThrough'
      'sep'
      'fontSize'
      'fontFamily'
      'color'
      'sep'
      'indent'
      'outdent'
      'formatBlock'
      'insertHorizontalRule'
      'blockStyle'
      'inlineStyle'
      'align'
      'sep'
      'table'
      'insertOrderedList'
      'insertUnorderedList'
      'sep'
      'subscript'
      'superscript'
      'sep'
      'createLink'
      'insertImage'
      'insertVideo'
      'uploadFile'
      'sep'
      'html'
      'removeFormat'
      'selectAll'
      'sep'
      'undo'
      'redo'
      'sep'
      'fullscreen'
    ]

    $('div#editor').on('editable.contentChanged editable.initialized', (e, editor) ->
      $('.preview').text editor.cleanTags(editor.getHTML())
      ).editable inlineMode: false

# ---
# generated by js2coffee 2.1.0

ready = ->
  init_editor()
  $(document).on "click", '.submit-wrapper', (ev) ->
    body = $('#post_body')[0]
    body.value = body.innerText
  $(".submit-wrapper").on('submit', )
  $("#new_post").on("ajax:success", (e, data, status, xhr) ->
    $("#new_post").replaceWith xhr.responseText
  ).on "ajax:error", (e, xhr, status, error) ->
    $("#new_post").append "<p>ERROR</p>"
################################################################################
# Initialize
################################################################################

$(document).ready ready
$(document).on 'page:load', ready
