
init_height = () ->
  console.log 'WOOT'
  h = $(window).height()
  $('section.home').css 'min-height', (h-224)
  $('section.contact').css 'min-height', (h-224)

# ---
# generated by js2coffee 2.1.0

ready = ->
  init_height()

  $("#new_post").on("ajax:success", (e, data, status, xhr) ->
    $("#new_post").replaceWith xhr.responseText
  ).on "ajax:error", (e, xhr, status, error) ->
    $("#new_post").append "<p>ERROR</p>"
################################################################################
# Initialize
################################################################################

$(document).ready ready
$(document).on 'page:load', ready
